### ISSUE TITLE
INFOGRAFÍA: Lenguajes de programación para contratos inteligentes.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Ferch0419#1]
[Lenguajes de programación para contratos inteligentes_Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Ferch0419/files/8596215/Lenguajes.de.programacion.para.contratos.inteligentes_Fernando.Miguel.Lopez.pdf)

**Comment by uzias10** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
